# --- IQL specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
runner: "episode"

buffer_size: 5000



obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train

agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
double_q: True
mixer: # Mixer becomes None

name: "iql"

# Hyperparams from paper
hiden_dim: 128
lr: 0.0005
standardise_rewards: False
use_rnn: True
evaluation_epsilon: 0.05
epsilon_anneal_time: 50000
target_update_interval_or_tau: 200
