runner: "parallel"
mac: "basic_mac"
name: "last_action_mappo"
obs_agent_id: True
obs_last_action: False
obs_individual_obs: False
obs_global_state: False
agent_output_type: "pi_logits"
learner: "ppo_learner"
action_selector: "soft_policies"
mask_before_softmax: True
hidden_dim: 128
lr: 0.0003
entropy_coef: 0.001
use_rnn: True
standardise_returns: False
standardise_rewards: True
q_nstep: 5
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
buffer_size: 10
batch_size_run: 10
batch_size: 10
target_update_interval_or_tau: 0.01
