# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False


# use the Q_Learner to train
mac: "non_shared_mac"
agent: "rnn_ns"
standardise_returns: False
standardise_rewards: True
use_rnn: False
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "vdn"

name: "vdn_ns"

