env: "gymma"

env_args:
  key: null
  time_limit: 50
  pretrained_wrapper: null
  initial_mode_ids: null
  switch_mode_ids: null
  fixed_switch_step: null

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
